username = "Bot-Name"
password = "Bot-Password"
client_id = "Bot-ID"
client_secret = "Bot-Secret"
outputdirdeuteranopia  = "daltonized/deuteranopia.jpg"
outputdirprotanopia = "daltonized/protanopia.jpg"
outputdirtritanopia = "daltonized/tritanopia.jpg"
imgur_client_id = "imgurclientid"