username = "Bot-Name"
password = "Bot-Password"
client_id = "Bot-ID"
client_secret = "Bot-Secret"
output_dir_deuteranopia  = "daltonized/deuteranopia.jpg"
output_dir_protanopia = "daltonized/protanopia.jpg"
output_dir_tritanopia = "daltonized/tritanopia.jpg"
imgur_client_id = "imgurclientid"